package pl.piomin.services.account.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "expenses")
public class Expense implements Serializable {
    private static final long serialVersionUID = 1L;

    private String id;
    private Date expenseDay;
    private Double value;
    private String category;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Date getExpenseDay() {
        return expenseDay;
    }

    public void setExpenseDay(Date expenseDay) {
        this.expenseDay = expenseDay;
    }

    @DynamoDBAttribute
    public Double getValue() {
        return value;
    }

    public void setValue(Double value) {
        this.value = value;
    }

    @DynamoDBRangeKey
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Override
    public String toString() {
        return "Expense{" +
                "id='" + id + '\'' +
                ", expenseDay=" + expenseDay +
                ", value=" + value +
                ", category='" + category + '\'' +
                '}';
    }
}
