package pl.piomin.services.account.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.xspec.S;

import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "plannings")
public class Planning implements Serializable {
    private static final long serialVersionUID = 1L;

    private String id;
    private String month;
    private String year;
    private String category;
    private Double value;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    @DynamoDBAttribute
    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @DynamoDBRangeKey
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @DynamoDBAttribute
    public Double getValue() {
        return value;
    }

    public void setValue(Double value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return "Planning{" +
                "id='" + id + '\'' +
                ", month='" + month + '\'' +
                ", year='" + year + '\'' +
                ", category='" + category + '\'' +
                ", value=" + value +
                '}';
    }
}
